CREATE TABLE users (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL
);

CREATE TABLE posts (
    ID NUMBER PRIMARY KEY,
    CONTENT CLOB,
    AUTHOR_ID NUMBER REFERENCES USERS(ID),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE subscriptions (
    ID NUMBER PRIMARY KEY,
    SUBSCRIBER_ID NUMBER REFERENCES USERS(ID),
    TARGET_AUTHOR_ID NUMBER REFERENCES USERS(ID)
);

-- 시퀀스
CREATE SEQUENCE subscription_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE post_seq START WITH 1 INCREMENT BY 1 NOCACHE;

-- 조회
SELECT * FROM users;
SELECT * FROM posts;
SELECT * FROM subscriptions;

-- 삭제
DROP SEQUENCE subscription_seq;
DROP SEQUENCE user_seq;
DROP SEQUENCE post_seq;

-- 유저 더미데이터
INSERT INTO USERS (ID, USERNAME) VALUES (USER_SEQ.NEXTVAL, '영희');
INSERT INTO USERS (ID, USERNAME) VALUES (USER_SEQ.NEXTVAL, '철수');
INSERT INTO USERS (ID, USERNAME) VALUES (USER_SEQ.NEXTVAL, '민수');

COMMIT;