name: ws_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.19.0
  http: ^1.4.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
